# WARNING: the artifactId below is hardcoded in two other places, neither of
# which can read this file. Changing it here means changing it in both:
#
#   - Dockerfile
#   - .github/workflows/*.yml
#
artifactId=azure-app-svc
group=com.rubensgomes
description=Spring Boot demo deployed to Azure App Service
title=Azure App Service Demo
mainClass=com.rubensgomes.azure.appsvc.App

# version must end in SNAPSHOT for release plugin to work due to bug reported at:
# https://stackoverflow.com/questions/79675543/gradle-release-plugin-not-merging-main-to-release
version=0.0.5-SNAPSHOT

